# ================== SERVER ==================
server.port=8084

# ================== SQL SERVER ==================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarStore;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=16062006

# ================== JPA ==================
# SỬA: Đổi từ update thành none để không cố tạo lại bảng đã có
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ================== INIT DATA (SQL Server) ==================
# SỬA: Tắt chế độ init mode để tránh chạy file data.sql gây trùng lặp dữ liệu
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

# ================== THYMELEAF ==================
spring.thymeleaf.cache=false

# ================== key gg ==================
spring.security.oauth2.client.registration.google.client-id=382693067445-oic63868dlj80g0l5hs76j9ajv5eq8p5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com