# ================== SERVER ==================
server.port=8082

# ================== SQL SERVER ==================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarStore;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123

# ================== JPA ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ================== INIT DATA (SQL Server) ==================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ================== THYMELEAF ==================
spring.thymeleaf.cache=false

# ================== key gg ==================
spring.security.oauth2.client.registration.google.client-id=382693067445-oic63868dlj80g0l5hs76j9ajv5eq8p5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com