# ================== SERVER ==================
server.port=8082

# ================== SQL SERVER ==================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarStore;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=17052005

# ================== JPA ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ================== INIT DATA (SQL Server) ==================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ================== THYMELEAF ==================
spring.thymeleaf.cache=false
